### ISSUE TITLE
Any chances for 1.20.2 backport?

### ISSUE THREAD

**Issue by sternschnaube** [Patbox/GlideAway#1]

**Comment by Patbox** [comment]
Generally not planned... is there any reason you can't update yourself?

**Comment by venaminecraft** [comment]
I don't like to ask for back ports / supporting older versions. But since it's all still in the same main version line, I felt fine with it. 

The reason is that I'm still not ready to update (lot of mods) but I would like to use this mod already. Maybe you can set it with really low priority on the list. Otherwise, I understand the extra work and I just have to wait it out 😊

**Comment by venaminecraft** [comment]
Updated now to 1.20.4 and personal no need anymore for a 1.20.2 version 😊 

Absolutely in love with GlideAway and PolyDecorations - big thanks!!!
